### ISSUE TITLE
NTFS SUPPORTED?

### ISSUE THREAD

**Issue by dedsecproyt** [bm0x/twrp_device_xiaomi_nabu#1]
Can i use my ntfs usb hdd  read-write on twrp? 

And what file system supports on twrp?

PS: Add TWRP for Mi Pad 5 Pro	elish

**Comment by bm0x** [comment]
hi, maybe, only see the recovery.fstab or twrp.flags

and the adding of Pad 5 Pro...

nabu and elish have different SoCs...

the only way is create another device tree with elish dump :D

**Comment by bm0x** [comment]
nabu have msmnile (860 Snap)
elish have kona (870 Snap)
